import React, { useState, useCallback } from 'react';
import { generateImageFromText } from '../services/geminiService';
import { Loader } from './Loader';
import { SparklesIcon } from './icons/SparklesIcon';
import { DownloadIcon } from './icons/DownloadIcon';
import { HistoryItem } from '../App';

interface GenerateTabProps {
  addToHistory: (item: Omit<HistoryItem, 'id' | 'timestamp'>) => void;
}

export const GenerateTab: React.FC<GenerateTabProps> = ({ addToHistory }) => {
  const [prompt, setPrompt] = useState<string>('');
  const [generatedImages, setGeneratedImages] = useState<string[]>([]);
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>('');

  const handleSubmit = useCallback(async () => {
    if (!prompt) {
      setError('Please enter a prompt to generate an image.');
      return;
    }
    setLoading(true);
    setError('');
    setGeneratedImages([]);
    setSelectedImage(null);
    try {
      const imageUrls = await generateImageFromText(prompt);
      addToHistory({
        type: 'generate',
        prompt,
        outputImages: imageUrls,
      });
      setGeneratedImages(imageUrls);
      setSelectedImage(imageUrls[0] || null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setLoading(false);
    }
  }, [prompt, addToHistory]);

  const handleDownloadImage = () => {
    if (!selectedImage) return;
    const a = document.createElement('a');
    a.href = selectedImage;
    a.download = 'ai-generated-image.png';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex flex-col space-y-6">
        <div>
          <label htmlFor="prompt-generate" className="block text-sm font-medium text-gray-300 mb-2">
            Image Description
          </label>
          <textarea
            id="prompt-generate"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., A futuristic cityscape at sunset, with flying cars and neon lights."
            className="w-full h-32 p-3 bg-gray-800 border border-gray-700 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition"
            disabled={loading}
          />
        </div>
        <button
          onClick={handleSubmit}
          disabled={loading || !prompt}
          className="w-full inline-flex justify-center items-center gap-2 px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 focus:ring-offset-gray-900 disabled:bg-gray-500 disabled:cursor-not-allowed transition"
        >
          {loading ? <Loader /> : <SparklesIcon />}
          Generate Image
        </button>
      </div>

      <div className="mt-8 bg-gray-800 rounded-lg p-6 min-h-[400px] flex items-center justify-center relative">
        {loading && <Loader size="lg" />}
        {error && <div className="text-red-400 bg-red-900/50 p-4 rounded-md">{error}</div>}
        {generatedImages.length > 0 && selectedImage && (
          <div className="w-full h-full flex flex-col items-center justify-center">
            <div className="relative mb-4">
              <img src={selectedImage} alt="Selected generated by AI" className="max-w-full max-h-[512px] h-auto rounded-lg shadow-lg object-contain" />
              <button
                onClick={handleDownloadImage}
                className="absolute top-4 right-4 inline-flex items-center gap-2 px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-black/50 hover:bg-black/75 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 focus:ring-offset-gray-800 transition"
                aria-label="Download generated image"
              >
                <DownloadIcon />
                <span>Download</span>
              </button>
            </div>
            {generatedImages.length > 1 && (
              <div className="flex space-x-2 overflow-x-auto p-2 w-full justify-center">
                {generatedImages.map((img, index) => (
                  <img
                    key={index}
                    src={img}
                    alt={`Generated thumbnail ${index + 1}`}
                    className={`w-20 h-20 object-cover rounded-md cursor-pointer border-2 transition-all ${selectedImage === img ? 'border-purple-500 scale-105' : 'border-transparent hover:border-gray-500'}`}
                    onClick={() => setSelectedImage(img)}
                  />
                ))}
              </div>
            )}
          </div>
        )}
        {!loading && !error && generatedImages.length === 0 && (
          <div className="text-center text-gray-500">
            <p>Your generated image will appear here.</p>
            <p className="text-sm">Enter a detailed description above and click "Generate".</p>
          </div>
        )}
      </div>
    </div>
  );
};
